package dev.jellystack.design.tv

import dev.jellystack.core.preferences.AppLanguage
import java.util.Locale

internal data class TvStrings(
    val home: String,
    val library: String,
    val search: String,
    val discover: String,
    val settings: String,
    val play: String,
    val continueLabel: String,
    val favorite: String,
    val watched: String,
    val loading: String,
    val retry: String,
    val quickConnect: String,
    val password: String,
    val connectJellyfin: String,
    val serverUrl: String,
    val displayName: String,
    val username: String,
    val connect: String,
    val usePassword: String,
    val newCode: String,
    val cancel: String,
    val quickConnectHelp: String,
    val enterCode: String,
    val noResults: String,
    val overview: String,
    val details: String,
    val episodes: String,
    val similar: String,
    val appearancePlayback: String,
    val settingsChooseCategory: String,
    val settingsAppearance: String,
    val settingsAppearanceDescription: String,
    val settingsPlaybackCategory: String,
    val settingsPlaybackDescription: String,
    val settingsAudioSubtitles: String,
    val settingsAudioSubtitlesDescription: String,
    val settingsSegmentSkippingDescription: String,
    val settingsConnectionsDescription: String,
    val quality: String,
    val audioLanguage: String,
    val subtitleLanguage: String,
    val autoplay: String,
    val resume: String,
    val playbackSpeed: String,
    val statsForNerds: String,
    val homeSections: String,
    val connections: String,
    val back: String,
    val close: String,
    val trailer: String,
    val recentlyAdded: String,
    val lastThirtyDays: String,
    val latestAdditions: String,
    val fromYourLibrary: String,
    val trailerPreviews: String,
    val trailerPreviewSound: String,
    val cast: String,
    val continueWatching: String,
    val nextUp: String,
    val recentShows: String,
    val recentMovies: String,
    val myMedia: String,
    val loadMore: String,
    val libraryLoadFailed: String,
    val jellyfinSearchFailed: String,
    val seerrSearchFailed: String,
    val discoverLoadFailed: String,
    val searchHint: String,
    val all: String,
    val connectSeerrPrompt: String,
    val requests: String,
    val cannotRequest: String,
    val request: String,
    val version: String,
    val standard: String,
    val seasons: String,
    val season: String,
    val requestProfile: String,
    val serverDefault: String,
    val sendRequest: String,
    val requesting: String,
    val noOverview: String,
    val language: String,
    val subtitleMode: String,
    val subtitleSize: String,
    val subtitleBackground: String,
    val seekBack: String,
    val seekForward: String,
    val on: String,
    val off: String,
    val connected: String,
    val remove: String,
    val addJellyfin: String,
    val addSeerr: String,
    val connectSeerr: String,
    val jellyfinAccount: String,
    val seerrAccount: String,
    val email: String,
    val nextEpisode: String,
    val playingInSeconds: String,
    val playNow: String,
    val audio: String,
    val subtitles: String,
    val speed: String,
    val stats: String,
    val more: String,
    val moreOptions: String,
    val syncPlay: String,
    val syncPlayNoPermission: String,
    val syncPlayUnauthorized: String,
    val syncPlayNetworkError: String,
    val syncPlayInvalidResponse: String,
    val preparingPlayback: String,
    val playbackFailedTitle: String,
    val playbackFailedMessage: String,
    val tvBeta: String,
    val tvTagline: String,
    val playback: String,
    val pause: String,
    val audioTrack: String,
    val subtitleTrack: String,
    val showStats: String,
    val hideStats: String,
    val mode: String,
    val container: String,
    val video: String,
    val resolution: String,
    val bitrate: String,
    val range: String,
    val droppedFrames: String,
    val joinedGroup: String,
    val useCurrentItemAsQueue: String,
    val leaveGroup: String,
    val createGroup: String,
    val joinGroup: String,
    val requestFailed: String,
    val automatic: String,
    val systemDefault: String,
    val english: String,
    val german: String,
    val small: String,
    val medium: String,
    val large: String,
    val none: String,
    val translucent: String,
    val dark: String,
    val forcedOnly: String,
    val preferredAlways: String,
    val preferredWhenAudioDiffers: String,
    val countdown: String,
    val immediate: String,
    val ask: String,
    val restart: String,
    val quickConnectDisabled: String,
    val quickConnectExpired: String,
    val serverUnreachable: String,
    val quickConnectFailed: String,
    val enterServerUrl: String,
    val jellyfinConnectionFailed: String,
    val manageJellyfin: String,
    val manageSeerr: String,
    val segmentSkipping: String,
    val serverSegmentExplanation: String,
    val introSegments: String,
    val recapSegments: String,
    val outroSegments: String,
    val previewSegments: String,
    val commercialSegments: String,
    val showSkipButton: String,
    val skipAutomatically: String,
    val skipIntro: String,
    val skipRecap: String,
    val skipPreview: String,
    val skipCommercial: String,
    val skipCredits: String,
    val playNextEpisode: String,
    val seasonNumber: String,
    val specials: String,
    val resumeAskTitle: String,
    val continueFrom: String,
    val trailerOpenFailed: String,
    val searching: String,
    val removeServerConfirm: String,
    val removeServerMessage: String,
    val pausedLabel: String,
    val detailUnavailable: String,
    val detailLoadFailed: String,
    val railTrending: String,
    val railPopularMovies: String,
    val railPopularShows: String,
    val railUpcomingMovies: String,
    val railUpcomingShows: String,
    val requestPending: String,
    val requestApproved: String,
    val requestDeclined: String,
    val requestFailedStatus: String,
    val requestCompleted: String,
    val requestUnknown: String,
    val availabilityAvailable: String,
    val availabilityProcessing: String,
    val availabilityPartiallyAvailable: String,
    val availabilityUnavailable: String,
    val modeDirect: String,
    val modeHls: String,
    val modeLocal: String,
) {
    companion object {
        fun current(language: AppLanguage): TvStrings {
            val german =
                language == AppLanguage.GERMAN ||
                    (language == AppLanguage.SYSTEM && Locale.getDefault().language == "de")
            return if (german) German else English
        }

        private val English =
            TvStrings(
                home = "Home",
                library = "Library",
                search = "Search",
                discover = "Discover",
                settings = "Settings",
                play = "Play",
                continueLabel = "Continue",
                favorite = "Favorite",
                watched = "Watched",
                loading = "Loading Jellystack",
                retry = "Try again",
                quickConnect = "Quick Connect",
                password = "Password",
                connectJellyfin = "Connect Jellyfin",
                serverUrl = "Server URL",
                displayName = "Display name",
                username = "Username",
                connect = "Connect",
                usePassword = "Use password",
                newCode = "Create a new code",
                cancel = "Cancel",
                quickConnectHelp =
                    "Open your Jellyfin profile on another device, choose Quick Connect, " +
                        "and enter this code.",
                enterCode = "Waiting for approval",
                noResults = "No results",
                overview = "Overview",
                details = "Details",
                episodes = "Episodes",
                similar = "Similar",
                appearancePlayback = "Playback and appearance",
                settingsChooseCategory = "Choose a category",
                settingsAppearance = "Appearance",
                settingsAppearanceDescription = "Language and home screen",
                settingsPlaybackCategory = "Playback",
                settingsPlaybackDescription = "Quality, autoplay, seeking and trailers",
                settingsAudioSubtitles = "Audio & Subtitles",
                settingsAudioSubtitlesDescription = "Languages, subtitle mode and appearance",
                settingsSegmentSkippingDescription = "Intro, recap, credits, previews and commercials",
                settingsConnectionsDescription = "Jellyfin and Seerr servers",
                quality = "Streaming quality",
                audioLanguage = "Preferred audio",
                subtitleLanguage = "Preferred subtitles",
                autoplay = "Autoplay next episode",
                resume = "Resume behavior",
                playbackSpeed = "Playback speed",
                statsForNerds = "Stats for Nerds",
                homeSections = "Server Home Sections",
                connections = "Server connections",
                back = "Back",
                close = "Close",
                trailer = "Trailer",
                recentlyAdded = "Recently added",
                lastThirtyDays = "Last 30 days",
                latestAdditions = "Latest additions",
                fromYourLibrary = "From your library",
                trailerPreviews = "Trailer previews",
                trailerPreviewSound = "Preview sound",
                cast = "Cast",
                continueWatching = "Continue watching",
                nextUp = "Next up",
                recentShows = "Recently added shows",
                recentMovies = "Recently added movies",
                myMedia = "My media",
                loadMore = "Load more",
                libraryLoadFailed = "This library could not be loaded.",
                jellyfinSearchFailed = "Jellyfin search failed.",
                seerrSearchFailed = "Seerr search failed.",
                discoverLoadFailed = "Discover could not be loaded.",
                searchHint = "Search Jellyfin and Seerr",
                all = "All",
                connectSeerrPrompt = "Connect Seerr in Settings to discover and request media.",
                requests = "Requests",
                cannotRequest = "Your Seerr account cannot request this media type.",
                request = "Request",
                version = "Version",
                standard = "Standard",
                seasons = "Seasons",
                season = "Season",
                requestProfile = "Request profile",
                serverDefault = "Server default",
                sendRequest = "Send request",
                requesting = "Requesting...",
                noOverview = "No overview available.",
                language = "Language",
                subtitleMode = "Subtitle mode",
                subtitleSize = "Subtitle size",
                subtitleBackground = "Subtitle background",
                seekBack = "Seek back",
                seekForward = "Seek forward",
                on = "On",
                off = "Off",
                connected = "Connected",
                remove = "Remove",
                addJellyfin = "Add Jellyfin",
                addSeerr = "Add Seerr",
                connectSeerr = "Connect Seerr",
                jellyfinAccount = "Jellyfin account",
                seerrAccount = "Seerr account",
                email = "Email",
                nextEpisode = "Next episode",
                playingInSeconds = "Playing in %d seconds",
                playNow = "Play now",
                audio = "Audio",
                subtitles = "Subtitles",
                speed = "Speed",
                stats = "Stats",
                more = "More",
                moreOptions = "More options",
                syncPlay = "SyncPlay",
                syncPlayNoPermission = "Your Jellyfin account cannot join SyncPlay groups.",
                syncPlayUnauthorized = "Sign in to Jellyfin again to use SyncPlay.",
                syncPlayNetworkError = "SyncPlay could not reach your Jellyfin server.",
                syncPlayInvalidResponse = "Jellyfin returned an invalid SyncPlay response.",
                preparingPlayback = "Preparing playback",
                playbackFailedTitle = "Playback could not continue",
                playbackFailedMessage =
                    "The player could not decode this stream. Try again to request a compatible version from Jellyfin.",
                tvBeta = "TV beta",
                tvTagline = "Your Jellyfin and Seerr library, designed for the big screen.",
                playback = "Playback",
                pause = "Pause",
                audioTrack = "Audio track %d",
                subtitleTrack = "Subtitle track %d",
                showStats = "Show Stats for Nerds",
                hideStats = "Hide Stats for Nerds",
                mode = "Mode",
                container = "Container",
                video = "Video",
                resolution = "Resolution",
                bitrate = "Bitrate",
                range = "Range",
                droppedFrames = "Dropped frames",
                joinedGroup = "Joined: %s",
                useCurrentItemAsQueue = "Use current item as queue",
                leaveGroup = "Leave group",
                createGroup = "Create Jellystack TV group",
                joinGroup = "Join %s",
                requestFailed = "The request could not be submitted.",
                automatic = "Automatic",
                systemDefault = "System default",
                english = "English",
                german = "German",
                small = "Small",
                medium = "Medium",
                large = "Large",
                none = "None",
                translucent = "Translucent",
                dark = "Dark",
                forcedOnly = "Forced only",
                preferredAlways = "Preferred language",
                preferredWhenAudioDiffers = "Preferred when audio differs",
                countdown = "Countdown",
                immediate = "Immediately",
                ask = "Always ask",
                restart = "Restart",
                quickConnectDisabled = "Quick Connect is disabled on this server.",
                quickConnectExpired = "The code expired. Create a new one.",
                serverUnreachable = "The server could not be reached.",
                quickConnectFailed = "Quick Connect failed. Check the server address.",
                enterServerUrl = "Enter a complete http:// or https:// server URL.",
                jellyfinConnectionFailed = "Could not connect to Jellyfin.",
                manageJellyfin = "Manage Jellyfin",
                manageSeerr = "Manage Seerr",
                segmentSkipping = "Segment skipping",
                serverSegmentExplanation =
                    "Uses segment markers supplied by your Jellyfin server. " +
                        "Availability depends on your server and media.",
                introSegments = "Intros",
                recapSegments = "Recaps",
                outroSegments = "Credits",
                previewSegments = "Previews",
                commercialSegments = "Commercials",
                showSkipButton = "Show skip button",
                skipAutomatically = "Skip automatically",
                skipIntro = "Skip intro",
                skipRecap = "Skip recap",
                skipPreview = "Skip preview",
                skipCommercial = "Skip commercial",
                skipCredits = "Skip credits",
                playNextEpisode = "Play next episode",
                seasonNumber = "Season %d",
                specials = "Specials",
                resumeAskTitle = "Resume playback?",
                continueFrom = "Continue from %s",
                trailerOpenFailed = "The trailer could not be opened.",
                searching = "Searching…",
                removeServerConfirm = "Remove %s?",
                removeServerMessage = "You will need to sign in again to use this server.",
                pausedLabel = "Paused",
                detailUnavailable = "This item is unavailable.",
                detailLoadFailed = "Details could not be loaded.",
                railTrending = "Trending",
                railPopularMovies = "Popular movies",
                railPopularShows = "Popular shows",
                railUpcomingMovies = "Upcoming movies",
                railUpcomingShows = "Upcoming shows",
                requestPending = "Pending",
                requestApproved = "Approved",
                requestDeclined = "Declined",
                requestFailedStatus = "Failed",
                requestCompleted = "Completed",
                requestUnknown = "Unknown",
                availabilityAvailable = "Available",
                availabilityProcessing = "Processing",
                availabilityPartiallyAvailable = "Partially available",
                availabilityUnavailable = "Unavailable",
                modeDirect = "Direct",
                modeHls = "Transcode (HLS)",
                modeLocal = "Local",
            )

        private val German =
            English.copy(
                home = "Start",
                library = "Bibliothek",
                search = "Suche",
                discover = "Entdecken",
                settings = "Einstellungen",
                play = "Abspielen",
                continueLabel = "Fortsetzen",
                favorite = "Favorit",
                watched = "Gesehen",
                loading = "Jellystack wird geladen",
                retry = "Erneut versuchen",
                quickConnect = "Quick Connect",
                password = "Passwort",
                connectJellyfin = "Jellyfin verbinden",
                serverUrl = "Server-URL",
                displayName = "Anzeigename",
                username = "Benutzername",
                connect = "Verbinden",
                usePassword = "Passwort verwenden",
                newCode = "Neuen Code erstellen",
                cancel = "Abbrechen",
                quickConnectHelp =
                    "Öffne dein Jellyfin-Profil auf einem anderen Gerät, wähle Quick Connect " +
                        "und gib diesen Code ein.",
                enterCode = "Warte auf Freigabe",
                noResults = "Keine Ergebnisse",
                overview = "Übersicht",
                details = "Details",
                episodes = "Folgen",
                similar = "Ähnliche Titel",
                appearancePlayback = "Wiedergabe und Darstellung",
                settingsChooseCategory = "Kategorie auswählen",
                settingsAppearance = "Darstellung",
                settingsAppearanceDescription = "Sprache und Startseite",
                settingsPlaybackCategory = "Wiedergabe",
                settingsPlaybackDescription = "Qualität, Autoplay, Spulen und Trailer",
                settingsAudioSubtitles = "Audio & Untertitel",
                settingsAudioSubtitlesDescription = "Sprachen, Untertitelmodus und Darstellung",
                settingsSegmentSkippingDescription = "Intro, Rückblick, Abspann, Vorschauen und Werbung",
                settingsConnectionsDescription = "Jellyfin- und Seerr-Server",
                quality = "Streamingqualität",
                audioLanguage = "Bevorzugter Ton",
                subtitleLanguage = "Bevorzugte Untertitel",
                autoplay = "Nächste Folge automatisch",
                resume = "Fortsetzen",
                playbackSpeed = "Wiedergabegeschwindigkeit",
                statsForNerds = "Stats for Nerds",
                homeSections = "Server-Startbereiche",
                connections = "Serververbindungen",
                back = "Zurück",
                close = "Schließen",
                trailer = "Trailer",
                recentlyAdded = "Neu hinzugefügt",
                lastThirtyDays = "Letzte 30 Tage",
                latestAdditions = "Zuletzt hinzugefügt",
                fromYourLibrary = "Aus deiner Mediathek",
                trailerPreviews = "Trailer-Vorschauen",
                trailerPreviewSound = "Vorschau-Ton",
                cast = "Besetzung",
                continueWatching = "Weiterschauen",
                nextUp = "Als Nächstes",
                recentShows = "Neu hinzugefügte Serien",
                recentMovies = "Neu hinzugefügte Filme",
                myMedia = "Meine Medien",
                loadMore = "Mehr laden",
                libraryLoadFailed = "Diese Bibliothek konnte nicht geladen werden.",
                jellyfinSearchFailed = "Die Jellyfin-Suche ist fehlgeschlagen.",
                seerrSearchFailed = "Die Seerr-Suche ist fehlgeschlagen.",
                discoverLoadFailed = "Entdecken konnte nicht geladen werden.",
                searchHint = "Jellyfin und Seerr durchsuchen",
                all = "Alle",
                connectSeerrPrompt = "Verbinde Seerr in den Einstellungen, um Medien zu entdecken und anzufragen.",
                requests = "Anfragen",
                cannotRequest = "Dein Seerr-Konto darf diesen Medientyp nicht anfragen.",
                request = "Anfragen",
                version = "Version",
                standard = "Standard",
                seasons = "Staffeln",
                season = "Staffel",
                requestProfile = "Anfrageprofil",
                serverDefault = "Serverstandard",
                sendRequest = "Anfrage senden",
                requesting = "Anfrage läuft...",
                noOverview = "Keine Beschreibung verfügbar.",
                language = "Sprache",
                subtitleMode = "Untertitelmodus",
                subtitleSize = "Untertitelgröße",
                subtitleBackground = "Untertitelhintergrund",
                seekBack = "Zurückspulen",
                seekForward = "Vorspulen",
                on = "An",
                off = "Aus",
                connected = "Verbunden",
                remove = "Entfernen",
                addJellyfin = "Jellyfin hinzufügen",
                addSeerr = "Seerr hinzufügen",
                connectSeerr = "Seerr verbinden",
                jellyfinAccount = "Jellyfin-Konto",
                seerrAccount = "Seerr-Konto",
                email = "E-Mail",
                nextEpisode = "Nächste Folge",
                playingInSeconds = "Wiedergabe in %d Sekunden",
                playNow = "Jetzt abspielen",
                audio = "Audio",
                subtitles = "Untertitel",
                speed = "Tempo",
                stats = "Statistiken",
                more = "Mehr",
                moreOptions = "Weitere Optionen",
                syncPlay = "SyncPlay",
                syncPlayNoPermission = "Dein Jellyfin-Konto darf keinen SyncPlay-Gruppen beitreten.",
                syncPlayUnauthorized = "Melde dich erneut bei Jellyfin an, um SyncPlay zu verwenden.",
                syncPlayNetworkError = "SyncPlay konnte deinen Jellyfin-Server nicht erreichen.",
                syncPlayInvalidResponse = "Jellyfin hat eine ungültige SyncPlay-Antwort gesendet.",
                preparingPlayback = "Wiedergabe wird vorbereitet",
                playbackFailedTitle = "Wiedergabe konnte nicht fortgesetzt werden",
                playbackFailedMessage =
                    "Der Player konnte diesen Stream nicht dekodieren. " +
                        "Versuche es erneut, um eine kompatible Version von Jellyfin anzufordern.",
                tvBeta = "TV-Beta",
                tvTagline = "Deine Jellyfin- und Seerr-Bibliothek - gemacht für den großen Bildschirm.",
                playback = "Wiedergabe",
                pause = "Pause",
                audioTrack = "Audiospur %d",
                subtitleTrack = "Untertitelspur %d",
                showStats = "Stats for Nerds anzeigen",
                hideStats = "Stats for Nerds ausblenden",
                mode = "Modus",
                container = "Container",
                video = "Video",
                resolution = "Auflösung",
                bitrate = "Bitrate",
                range = "Dynamikumfang",
                droppedFrames = "Verworfene Frames",
                joinedGroup = "Beigetreten: %s",
                useCurrentItemAsQueue = "Aktuellen Titel als Warteschlange verwenden",
                leaveGroup = "Gruppe verlassen",
                createGroup = "Jellystack-TV-Gruppe erstellen",
                joinGroup = "%s beitreten",
                requestFailed = "Die Anfrage konnte nicht gesendet werden.",
                automatic = "Automatisch",
                systemDefault = "Systemstandard",
                english = "Englisch",
                german = "Deutsch",
                small = "Klein",
                medium = "Mittel",
                large = "Groß",
                none = "Keiner",
                translucent = "Halbtransparent",
                dark = "Dunkel",
                forcedOnly = "Nur erzwungene",
                preferredAlways = "Bevorzugte Sprache",
                preferredWhenAudioDiffers = "Bevorzugt bei abweichendem Ton",
                countdown = "Countdown",
                immediate = "Sofort",
                ask = "Immer fragen",
                restart = "Neu starten",
                quickConnectDisabled = "Quick Connect ist auf diesem Server deaktiviert.",
                quickConnectExpired = "Der Code ist abgelaufen. Erstelle einen neuen.",
                serverUnreachable = "Der Server konnte nicht erreicht werden.",
                quickConnectFailed = "Quick Connect ist fehlgeschlagen. Prüfe die Serveradresse.",
                enterServerUrl = "Gib eine vollständige Server-URL mit http:// oder https:// ein.",
                jellyfinConnectionFailed = "Die Verbindung zu Jellyfin ist fehlgeschlagen.",
                manageJellyfin = "Jellyfin verwalten",
                manageSeerr = "Seerr verwalten",
                segmentSkipping = "Segmente überspringen",
                serverSegmentExplanation =
                    "Verwendet Segmentmarkierungen deines Jellyfin-Servers. " +
                        "Die Verfügbarkeit hängt von Server und Medium ab.",
                introSegments = "Intros",
                recapSegments = "Rückblicke",
                outroSegments = "Abspann",
                previewSegments = "Vorschauen",
                commercialSegments = "Werbung",
                showSkipButton = "Schaltfläche anzeigen",
                skipAutomatically = "Automatisch überspringen",
                skipIntro = "Intro überspringen",
                skipRecap = "Rückblick überspringen",
                skipPreview = "Vorschau überspringen",
                skipCommercial = "Werbung überspringen",
                skipCredits = "Abspann überspringen",
                playNextEpisode = "Nächste Folge abspielen",
                seasonNumber = "Staffel %d",
                specials = "Spezialfolgen",
                resumeAskTitle = "Wiedergabe fortsetzen?",
                continueFrom = "Ab %s fortsetzen",
                trailerOpenFailed = "Der Trailer konnte nicht geöffnet werden.",
                searching = "Suche läuft…",
                removeServerConfirm = "%s entfernen?",
                removeServerMessage =
                    "Du musst dich erneut anmelden, um diesen Server zu verwenden.",
                pausedLabel = "Pausiert",
                detailUnavailable = "Dieser Titel ist nicht verfügbar.",
                detailLoadFailed = "Details konnten nicht geladen werden.",
                railTrending = "Angesagt",
                railPopularMovies = "Beliebte Filme",
                railPopularShows = "Beliebte Serien",
                railUpcomingMovies = "Kommende Filme",
                railUpcomingShows = "Kommende Serien",
                requestPending = "Ausstehend",
                requestApproved = "Genehmigt",
                requestDeclined = "Abgelehnt",
                requestFailedStatus = "Fehlgeschlagen",
                requestCompleted = "Abgeschlossen",
                requestUnknown = "Unbekannt",
                availabilityAvailable = "Verfügbar",
                availabilityProcessing = "In Verarbeitung",
                availabilityPartiallyAvailable = "Teilweise verfügbar",
                availabilityUnavailable = "Nicht verfügbar",
                modeDirect = "Direkt",
                modeHls = "Transcode (HLS)",
                modeLocal = "Lokal",
            )
    }
}
