package dev.jellystack.core.jellyfin

import dev.jellystack.core.profile.MediaProviderIds

data class JellyfinLibrary(
    val id: String,
    val name: String,
    val collectionType: String?,
    val itemCount: Long?,
    val primaryImageTag: String?,
)

data class JellyfinItem(
    val id: String,
    val libraryId: String?,
    val name: String,
    val sortName: String?,
    val overview: String?,
    val type: String,
    val mediaType: String?,
    val locationType: String?,
    val taglines: List<String>,
    val parentId: String?,
    val primaryImageTag: String?,
    val thumbImageTag: String?,
    val backdropImageTag: String?,
    val seriesId: String?,
    val seriesPrimaryImageTag: String?,
    val seriesThumbImageTag: String?,
    val seriesBackdropImageTag: String?,
    val parentLogoImageTag: String?,
    val runTimeTicks: Long?,
    val positionTicks: Long?,
    val playedPercentage: Double?,
    val productionYear: Int?,
    val premiereDate: String?,
    val communityRating: Double?,
    val officialRating: String?,
    val indexNumber: Int?,
    val parentIndexNumber: Int?,
    val seriesName: String?,
    val seasonId: String?,
    val episodeTitle: String?,
    val lastPlayed: String?,
    val dateCreated: String? = null,
    val logoImageTag: String? = null,
    val artImageTag: String? = null,
    val bannerImageTag: String? = null,
    val seriesLogoImageTag: String? = null,
    val seriesArtImageTag: String? = null,
    val seriesBannerImageTag: String? = null,
    val providerIds: MediaProviderIds = MediaProviderIds(sourceLocalId = id),
)

data class JellyfinItemDetail(
    val id: String,
    val name: String,
    val overview: String?,
    val taglines: List<String>,
    val runTimeTicks: Long?,
    val productionYear: Int?,
    val premiereDate: String?,
    val communityRating: Double?,
    val officialRating: String?,
    val genres: List<String>,
    val studios: List<String>,
    val primaryImageTag: String?,
    val backdropImageTags: List<String>,
    val mediaSources: List<JellyfinMediaSource>,
    val isFavorite: Boolean = false,
    val isPlayed: Boolean = false,
    val providerIds: Map<String, String> = emptyMap(),
    val originalTitle: String? = null,
    val originalLanguage: String? = null,
    val criticRating: Double? = null,
    val productionLocations: List<String> = emptyList(),
    val tags: List<String> = emptyList(),
    val logoImageTag: String? = null,
    val people: List<JellyfinPerson> = emptyList(),
    val parentBackdropImageTags: List<String> = emptyList(),
)

data class JellyfinPerson(
    val id: String,
    val name: String,
    val role: String?,
    val type: String?,
    val primaryImageTag: String?,
)

data class JellyfinMediaSource(
    val id: String,
    val name: String?,
    val runTimeTicks: Long?,
    val container: String?,
    val videoBitrate: Int?,
    val supportsDirectPlay: Boolean,
    val supportsDirectStream: Boolean,
    val supportsTranscoding: Boolean,
    val streams: List<JellyfinMediaStream>,
)

data class JellyfinMediaStream(
    val type: JellyfinMediaStreamType,
    val index: Int?,
    val displayTitle: String?,
    val codec: String?,
    val language: String?,
    val isDefault: Boolean,
    val isForced: Boolean,
    val bitrate: Int? = null,
    val width: Int? = null,
    val height: Int? = null,
    val profile: String? = null,
    val videoRange: String? = null,
    val videoRangeType: String? = null,
    val averageFrameRate: Double? = null,
    val bitDepth: Int? = null,
    val channels: Int? = null,
    val channelLayout: String? = null,
    val isExternal: Boolean = false,
    val isHearingImpaired: Boolean = false,
)

enum class JellyfinMediaStreamType {
    VIDEO,
    AUDIO,
    SUBTITLE,
    OTHER,
}
