name: Experimental iOS

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ios:
    runs-on: macos-14
    env:
      CI: true
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Set up JDK
        uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9 # v4
        with:
          distribution: temurin
          java-version: 17

      - name: Gradle wrapper permissions
        run: chmod +x gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@ed408507eac070d1f99cc633dbcf757c94c7933a # v4

      - name: Compile iOS and run simulator tests
        run: >-
          ./gradlew
          :shared-core:iosSimulatorArm64Test
          :shared-network:iosSimulatorArm64Test
          :shared-database:iosSimulatorArm64Test
          :players:iosSimulatorArm64Test
          :design:iosSimulatorArm64Test
          :app-ios:iosSimulatorArm64Test
          :app-ios:linkDebugFrameworkIosSimulatorArm64
          :app-ios:linkReleaseFrameworkIosSimulatorArm64
          --stacktrace
